### ISSUE TITLE
Did you get permissions of these individual datasets? 

### ISSUE THREAD

**Issue by nlp4869** [chineseGLUE/chineseGLUE#1]
Just wonder, as there is no description paper on how your `chineseglue` inherit from previous Chinese NLP datasets, and it seems to be an ONGOING work rather than a completed work. For example, as LCQMC dataset is not publicly available, is it legal to put them here without permission by the original authors, or did you get permission?

**Comment by brightmart** [comment]
hi. thank you for your reminder. 

these databasets are public available on the github or internet, we will include the source in the Reference part.  we will just follow license of datasets.

**Comment by nghuyong** [comment]
This is a wonderful project, but I have the same problem, do you get the permission of the source dataset?
Although some databasets are available on Github, but if following their licenses, they are not publicly available.

**Comment by brightmart** [comment]
One obstruct currently in natural language processing in Chinese is there are too few widely used datasets available to public. 

The mission of chineseGLUE is make datasets accessable for anyone anywhere, and being evaluated publicly, just as what GLUE did, so that it can be for the good of community.

we will contact with authors at meaning time.

**Comment by nghuyong** [comment]
Nice ~

**Comment by brightmart** [comment]
do you interested in make your contribution for chineseGLUE? @nghuyong @nlp4869 
you can join with us on qq group:  836811304

**Comment by nghuyong** [comment]
OK, That's my pleasure!

**Comment by Gdls** [comment]
Hi, a wonderful work. But would you please draw back the LCQMC dataset in the download files first, since at present the dataset is publicly available only by the application from the authors.

**Comment by nlp4869** [comment]
@brightmart 
I don't think you realize what you've done does not show respect to the original authors of these datasets (and you are trying to BEAUTIFY the title of this issue, which is disappointing). 
**You MUST get permissions FIRST before you boldly say 'you are contributing to the Chinese NLP community'.**
The project is great, but the way you do is awful.

**Comment by brightmart** [comment]
sorry. link of LCQMC is not available now.
