### ISSUE TITLE
数据集下载失败

### ISSUE THREAD

**Issue by narrowview** [chineseGLUE/chineseGLUE#12]
![image](https://user-images.githubusercontent.com/12960028/66534606-51dba580-eb49-11e9-8dcc-0d581363204d.png)

![image](https://user-images.githubusercontent.com/12960028/66534617-599b4a00-eb49-11e9-9200-297d1c944617.png)

点击数据集下载报如上图问题

**Comment by brightmart** [comment]
现在好了，你再试一试。LCQMC数据集，你去向作者请求，或在去网上搜一搜。
