### ISSUE TITLE
能说一下设备要求吗

### ISSUE THREAD

**Issue by captain2017** [chineseGLUE/chineseGLUE#13]
1080ti反应内存不够。InternalError: Dst tensor is not initialized

**Comment by brightmart** [comment]
这个和bert一样的：

System | Seq Length | Max Batch Size
-- | -- | --
BERT-Base | 64 | 64
... | 128 | 32
... | 256 | 16
... | 320 | 14
... | 384 | 12
... | 512 | 6
BERT-Large | 64 | 12
... | 128 | 6
... | 256 | 2
... | 320 | 1
... | 384 | 0
... | 512 | 0
