### ISSUE TITLE
调小了batchsize，不行！

### ISSUE THREAD

**Issue by captain2017** [chineseGLUE/chineseGLUE#14]
![image](https://user-images.githubusercontent.com/27909557/66629354-0d790400-ec34-11e9-96c8-13575ee5c7f9.png)

**Comment by brightmart** [comment]
可能是序列长度有不一致吧。batch size应该没问题。

**Comment by captain2017** [comment]
序列长度不能修改吗

**Comment by brightmart** [comment]
fine-tuning长度可以根据任务来调整；

如果你要预训练，那么生成tfreocrds的时候的长度和后续训练、调优的长度要一致，。

**Comment by captain2017** [comment]
CURRENT_DIR=`pwd`
export CUDA_VISIBLE_DEVICES="1"
export ALBERT_CONFIG_DIR=$CURRENT_DIR/albert_config
export ALBERT_XLARGE_DIR=$CURRENT_DIR/prev_trained_model/albert_xlarge_zh
export GLUE_DIR=$CURRENT_DIR/../../glue/chineseGLUEdatasets/

python run_classifier.py \
  --task_name=tnews \
  --do_train=true \
  --do_eval=true \
  --data_dir=$GLUE_DIR/tnews \
  --vocab_file=$ALBERT_CONFIG_DIR/vocab.txt \
  --bert_config_file=$ALBERT_CONFIG_DIR/albert_config_large.json \
  --init_checkpoint=$ALBERT_XLARGE_DIR/albert_model.ckpt \
  --max_seq_length=64 \
  --train_batch_size=12 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  --output_dir=$CURRENT_DIR/tnews_output/

**Comment by captain2017** [comment]
--max_seq_length=64变成--max_seq_length=128就行了
