### ISSUE TITLE
albert_tiny结果无法复现,请教.

### ISSUE THREAD

**Issue by hxyshare** [chineseGLUE/chineseGLUE#47]
|          | TNEWS | LCQMC | XNLI | INEWS | DRCD               | CMRC2018           |
|----------|-------|-------|------|-------|--------------------|--------------------|
| 原始结果 | 87.1 | 85.4  | 68.0 | 81.4  | F1:80.67,EM: 71.6             |F1: 73.95, EM:48.31             |
| 复现结果 | 82.4  | 80.9  | 66.7 | 62.9  | F1: 76.3, EM: 64.5 | F1: 67.9, EM: 43.1 |

您好,这是我用README中相同参数跑出来的结果,使用的是10月15日预训练的权重,但是INEWS和两个阅读理解任务相差过大.
想请教下,是有一些调参的trick和数据的预处理吗?

**Comment by brightmart** [comment]
你这差的有点多啊。能否提供一下相关的信息？ 默认情况下我们报告的是在测试集上test的结果。

比如LCQMC，使用我们的代码，不用额外数据数据。最重要的参数如：
--max_seq_length=128 --train_batch_size=64   --learning_rate=1e-4   --num_train
学习率可以尝试不同的学习率，如下： {2e-5, 6e-5, 1e-4} 

1、是在什么样的机器上做实验的呢；
2、能否把LCQMC的训练参数贴出来；

你也可以使用最新的tiny的预训练模型去尝试。

**Comment by hxyshare** [comment]
|          | INEWS | DRCD               | CMRC2018            | LCQMC |
|----------|-------|--------------------|---------------------|-------|
| 原始结果 | 81.4  | F1:80.67,EM: 71.6  | F1: 73.95, EM:48.31 | 85.4  |
| 复现结果 | 67.4  | F1: 77.59, EM:66.9 | F1: 70.66, EM:47.00 | 79.5  |

拿新的权重(albert_tiny_250k)重新跑了下,现在的结果,感觉好点.
1、是在什么样的机器上做实验的呢； 使用的是v100  16G
2、能否把LCQMC的训练参数贴出来；使用的参数和[中文任务基准测评(chineseGLUE)-排行榜-各任务对比](https://github.com/chineseGLUE/chineseGLUE#%E4%B8%AD%E6%96%87%E4%BB%BB%E5%8A%A1%E5%9F%BA%E5%87%86%E6%B5%8B%E8%AF%84chineseglue-%E6%8E%92%E8%A1%8C%E6%A6%9C-%E5%90%84%E4%BB%BB%E5%8A%A1%E5%AF%B9%E6%AF%94)一致.

主要是inews这个任务结果有点差,参数:
```
--num_train_epochs=3
--train_batch_size=32 
--max_seq_length=512 
--learning_rate=2e-5
--warmup_proportion=0.1
```
还有LCQMC参数:
```
--train_batch_size=32 
--max_seq_length=128 
 --learning_rate=2e-5
--num_train_epochs=3
--warmup_proportion=0.1
```
不知道原因.

**Comment by brightmart** [comment]
你好，有两个问题：
1、你可以尝试不用的学习率来获得最好效果 {2e-5, 6e-5, 1e-4}， num_train_epochs可以设置为5，train_batch_size 可以设置为64；

2、我们看的是测试集上的效果，报告的是在所有保存的checkpoint上测试集上最好的效果。你是不是只看看了最后的checkpoint上的效果了呢。在仔细看日志的最后一些内容，会在数据集所在目录生成一个文件的，可以看到各个checkpoint的效果。
![image](https://user-images.githubusercontent.com/19634224/67408022-f13d7580-f5ea-11e9-811c-14104536e11c.png)

**Comment by brightmart** [comment]
是否方便加一下QQ群（群号:836811304），给你技术支持一下。

**Comment by hxyshare** [comment]
感谢回复,我试试您的意见.超参数我再调一下,checkpoint那边确实有问题,不是每1000步就eval一下,看是否保存.

**Comment by brightmart** [comment]
每1000步就会保存checkpoint,然后验证的时候所以的checkpoint都会在验证集上跑分。怎么样了？

**Comment by hxyshare** [comment]
结果会好一点
