### ISSUE TITLE
“BQ 智能客服问句匹配”数据集描述似乎有误

### ISSUE THREAD

**Issue by sandove** [chineseGLUE/chineseGLUE#59]
按链接下载数据集后，与“ccks2018_task3”文件夹内数据核对有出入。
1. “共有120,000对句子对”  →    “共有100,000对句子对”
2. “数据量：训练集(100,000)，验证集(10,000)，测试集(10,000)”   → 
    “数据量：训练集(70,000)，验证集(20,000)，测试集(10,000)”

**Comment by enningxie** [comment]
> 按链接下载数据集后，与“ccks2018_task3”文件夹内数据核对有出入。
> 
> 1. “共有120,000对句子对”  →    “共有100,000对句子对”
> 2. “数据量：训练集(100,000)，验证集(10,000)，测试集(10,000)”   →
>    “数据量：训练集(70,000)，验证集(20,000)，测试集(10,000)”

ccks2018_task3使用数据集为BQ数据集train部分，BQ数据集请到[这里](http://icrc.hitsz.edu.cn/info/1037/1162.htm)下载。
