### ISSUE TITLE
有关数据集与评测指标的问题

### ISSUE THREAD

**Issue by kinghuin** [chineseGLUE/chineseGLUE#60]
Hi，请问ChineseGLUE中的THUCTC的train/dev/test是如何划分的，是否有计划公布处理好的数据集？以及是否有计划上线到榜单上呢？

**Comment by kinghuin** [comment]
此外，我注意到chineseGLUE  cmrc2018文件夹中的数据集标题是cmrc2019，是不是里面放错文件了？

**Comment by brightmart** [comment]
有的，明天可以。稍后澄清一下

**Comment by kinghuin** [comment]
@brightmart 请问数据集有更新吗？在ChineseGLUE中各个数据集的评测指标是什么呢？

**Comment by brightmart** [comment]
数据集已经更新了。
默认指标是在测试集上的准确率。
11月9日，我们会发布一个arxiv文章，也会做详细介绍。

**Comment by kinghuin** [comment]
@brightmart 我注意到榜单又新增了iFLYTEKData数据集  请问这个数据集大概什么时候会公布呢？

**Comment by brightmart** [comment]
这个应该已经在上面了；你看看下载的压缩包里有没有？

**Comment by kinghuin** [comment]
@brightmart 是的 压缩包里面还没有iFLYTEKData

**Comment by brightmart** [comment]
好的。https://storage.googleapis.com/chineseglue/tasks/iflytek.zip

**Comment by kinghuin** [comment]
@brightmart  感谢~ :)
