### ISSUE TITLE
推荐两个自然语言推理数据集

### ISSUE THREAD

**Issue by zengjunjun** [chineseGLUE/chineseGLUE#64]
该数据集是从原始英文数据集翻译而来（SNLI，和MNLI），另外quora question pairs 由于版权不明，目前没有开放。能否考虑下该数据集，所有数据集都有bert作为基线进行了评测。谢谢
https://github.com/zengjunjun/CNSD

**Comment by brightmart** [comment]
点赞！我们有同学研究这类推理的，可以考虑加入，这就联系专业同学做评估。

**Comment by zengjunjun** [comment]
Thanks
