### ISSUE TITLE
评测系统“上传失败”

### ISSUE THREAD

**Issue by kinghuin** [chineseGLUE/chineseGLUE#73]
Hi 我尝试在ChineseGLUE提交我本地测试超越SOTA的实验结果但显示“上传失败” 请问我应该如何上传实验结果呢？

**Comment by YC-wind** [comment]
你微信多少呢

**Comment by kinghuin** [comment]
@YC-wind 656612149

**Comment by kinghuin** [comment]
谢谢 :)    微信帮助下已解决，错误原因：上传文件的行数不正确
