### ISSUE TITLE
是否可以提供统一的数据集下载

### ISSUE THREAD

**Issue by bigsunkt** [chineseGLUE/chineseGLUE#74]
仅作测评感觉使用范围还是有限，真正有价值的是数据，有的数据集需要单独联系下载，那就还是没有解决根本问题，这个项目如果可以提供所有的数据下载，在这基础上做评估，会更有意义。

**Comment by bigsunkt** [comment]
好的我说的其实是LCQMC的数据~

**Comment by brightmart** [comment]
感谢反馈。能否加一下我们的QQ群，方便后续交流
