### ISSUE TITLE
数据集描述可以更加清晰

### ISSUE THREAD

**Issue by TankAbraham** [ChineseGLUE/ChineseGLUE#82]
您好，

chineseGLUEdatasets.v0.0.1.zip压缩包中，共包含9个文件夹，但是在readme中却给出了12个数据集的描述。
这样一来会让刚接触该数据集的同学误以为自己的下载到的压缩包有遗漏。
所以能否使得chineseGLUEdatasets.v0.0.1.zip压缩包中包含12个文件夹，每个文件夹按照数据集的名字来命名（正如当前的您的做法）。

**Comment by brightmart** [comment]
你好，有一部分新的数据集安排在这里了：
https://github.com/CLUEbenchmark/CLUE
